"""first

Revision ID: 436dc64bf5dc
Revises: 
Create Date: 2021-12-01 11:19:31.892794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436dc64bf5dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('userstatus', sa.String(length=5), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('medicine',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('manufacturer', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('demand', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.cid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('orders',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('shipDate', sa.DateTime(timezone=6), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('orders_medicine',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.mid'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.oid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_medicine')
    op.drop_table('orders')
    op.drop_table('medicine')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
